### ISSUE TITLE
Expired SSL certificates

### ISSUE THREAD

**Issue by tanordheim** [kelseyhightower/journal-2-logentries#9]
It seems that the embedded certificates in https://github.com/kelseyhightower/journal-2-logentries/blob/master/logentries/certs.go expired yesterday, and our running journal-2-logentries containers are crashing with the error `x509: certificate signed by unknown authority`.

I'm forking the repo and disabling SSL certificate validation for now, but this should probably be updated in the code too. I've contacted Logentries about this as well, as the page referenced in `certs.go` have not been updated and still contains expired certificates. I can make a pull request with some changes here once I receive something - I'm creating a ticket for visibility right now, or if someone else has a more imminent fix for it.

**Comment by benjaminbarbe** [comment]
Do you have any news on this? 👍

**Comment by tanordheim** [comment]
https://github.com/kelseyhightower/journal-2-logentries/pull/10 has been opened by the people at Logentries themselves, as far as I've understood, and are awaiting merge.

**Comment by tanordheim** [comment]
I should in fact close this issue, since #10 contains both a description of the problem and a fix - which does issue does not.
